// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/image/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve la metadata y URL de una imagen del usuario autenticado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Obtener información de una imagen",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la imagen",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ImageDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/images/{id}/transform": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Aplica transformaciones (resize, crop, rotación, filtros) a una imagen previamente cargada por el usuario",
                "produces": [
                    "image/png",
                    "image/jpeg",
                    "image/gif"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Aplica transformaciones a una imagen",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la imagen",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Parámetros de transformación",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TransformationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Imagen transformada",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/images/{rest}": {
            "get": {
                "description": "Devuelve el archivo de imagen almacenado en el servidor desde la carpeta local \"uploads\", sin exponer su ruta real.",
                "produces": [
                    "image/jpeg",
                    "image/png",
                    "image/gif"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Servir imagen",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Ruta relativa de la imagen (por ejemplo: user123/imagen.jpg)",
                        "name": "rest",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "403": {
                        "description": "Acceso prohibido",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Archivo no encontrado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Autentica al usuario y devuelve un token JWT si las credenciales son correctas.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Inicia sesión",
                "parameters": [
                    {
                        "description": "Credenciales de usuario",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseLogin"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Crea un nuevo usuario en la base de datos con nombre de usuario y contraseña.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Registra un nuevo usuario",
                "parameters": [
                    {
                        "description": "Datos del usuario a registrar",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permite a un usuario autenticado subir una imagen. Se guarda en MinIO y se almacena la metadata.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Sube una imagen",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Imagen a subir (jpg, jpeg, png, gif)",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.UploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user-images": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve las imágenes subidas por el usuario autenticado con soporte de paginación.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Lista imágenes del usuario autenticado",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Número de página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Cantidad por página",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PaginatedImagesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Descripción del error"
                }
            }
        },
        "models.Image": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "format": {
                    "description": "Formato (jpeg, png, etc.)",
                    "type": "string"
                },
                "height": {
                    "description": "Alto de la imagen",
                    "type": "integer"
                },
                "image_id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "description": "Ruta en el servidor",
                    "type": "string"
                },
                "size": {
                    "description": "Tamaño en bytes",
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                },
                "user_name": {
                    "type": "string"
                },
                "width": {
                    "description": "Ancho de la imagen",
                    "type": "integer"
                }
            }
        },
        "models.ImageDetailResponse": {
            "type": "object",
            "properties": {
                "format": {
                    "type": "string",
                    "example": "jpeg"
                },
                "height": {
                    "type": "integer",
                    "example": 1080
                },
                "name": {
                    "type": "string",
                    "example": "imagen123.jpg"
                },
                "size": {
                    "type": "integer",
                    "example": 204800
                },
                "url": {
                    "type": "string",
                    "example": "http://localhost:8080/images/rodrick/imagen123.jpg"
                },
                "width": {
                    "type": "integer",
                    "example": 1920
                }
            }
        },
        "models.PaginatedImagesResponse": {
            "type": "object",
            "properties": {
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Image"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.ResponseLogin": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "models.TransformationRequest": {
            "type": "object",
            "properties": {
                "transformations": {
                    "description": "Transformaciones a aplicar a la imagen",
                    "type": "object",
                    "properties": {
                        "crop": {
                            "description": "Recortar la imagen",
                            "type": "object",
                            "properties": {
                                "height": {
                                    "description": "Alto del recorte\nexample: 300",
                                    "type": "integer"
                                },
                                "width": {
                                    "description": "Ancho del recorte\nexample: 400",
                                    "type": "integer"
                                },
                                "x": {
                                    "description": "Posición X del recorte\nexample: 100",
                                    "type": "integer"
                                },
                                "y": {
                                    "description": "Posición Y del recorte\nexample: 50",
                                    "type": "integer"
                                }
                            }
                        },
                        "filters": {
                            "description": "Filtros a aplicar",
                            "type": "object",
                            "properties": {
                                "grayscale": {
                                    "description": "Convertir a escala de grises\nexample: true",
                                    "type": "boolean"
                                },
                                "sepia": {
                                    "description": "Aplicar filtro sepia\nexample: false",
                                    "type": "boolean"
                                }
                            }
                        },
                        "format": {
                            "description": "Formato de salida de la imagen (png, jpg, gif)\nexample: jpg",
                            "type": "string"
                        },
                        "resize": {
                            "description": "Redimensionar la imagen",
                            "type": "object",
                            "properties": {
                                "height": {
                                    "description": "Alto en píxeles\nexample: 600",
                                    "type": "integer"
                                },
                                "width": {
                                    "description": "Ancho en píxeles\nexample: 800",
                                    "type": "integer"
                                }
                            }
                        },
                        "rotate": {
                            "description": "Rotar la imagen (en grados)\nexample: 90",
                            "type": "number"
                        }
                    }
                }
            }
        },
        "models.UploadResponse": {
            "type": "object",
            "properties": {
                "image": {
                    "$ref": "#/definitions/models.UploadedImageDetail"
                },
                "message": {
                    "type": "string",
                    "example": "Imagen subida exitosamente"
                }
            }
        },
        "models.UploadedImageDetail": {
            "type": "object",
            "properties": {
                "format": {
                    "type": "string",
                    "example": "jpeg"
                },
                "height": {
                    "type": "integer",
                    "example": 1080
                },
                "name": {
                    "type": "string",
                    "example": "imagen123.jpg"
                },
                "size": {
                    "type": "integer",
                    "example": 204800
                },
                "url": {
                    "type": "string",
                    "example": "http://localhost:8080/images/username/imagen123.jpg"
                },
                "width": {
                    "type": "integer",
                    "example": 1920
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API de Procesamiento de Imágenes",
	Description:      "Esta es una API para subir, transformar y consultar imágenes.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
